### ISSUE TITLE
Installation error: `ModuleNotFoundError: No module named 'distutils.msvccompiler'`

### ISSUE THREAD

**Issue by MisterEyMan** [FormerLurker/ArcWelderPlugin#239]
I have Octoprint setup on my DietPi.  When trying to install Arc Welder I get:
```
root@DietPi:~# pip install "https://github.com/FormerLurker/ArcWelderPlugin/archive/master.zip"
Collecting https://github.com/FormerLurker/ArcWelderPlugin/archive/master.zip
  Downloading https://github.com/FormerLurker/ArcWelderPlugin/archive/master.zip
     / 200.1 kB 657.6 kB/s 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-0xt8qnjh/setup.py", line 32, in <module>
          from distutils.msvccompiler import MSVCCompiler
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I have searched in vain for that error but no luck. Any ideas?  
Thanks.

**Comment by kamilko** [comment]
This issue still exists in setup DietPi+OctoPrint from software manager. Everything installed fresh on 2024.12.01. on raspberry pi.

**Comment by gisforgirard** [comment]
https://github.com/pypa/setuptools/issues/4620#issuecomment-2323233905

**Comment by gcfrxbots** [comment]
I know this is old but I had this same problem and managed to fix it. Here's my steps, and the modified file: 

1. Enable the web SSH server on Octoprint (I'm using Octo4a on an old Android), and connect to the terminal by navigating to octoprint.ip.address:5002 and signing in with the credentials specified within the server. 

2. Run the following command: 
/home/octoprint/octoprint-venv/bin/python3 -m pip install "setuptools==73.0.1; python_version >= '3.8'" "setuptools; python_version < '3.8'"

3. This won't fix it, at least it didn't for me. The plugin has an outdated dependency. I downloaded it and fixed the dependency, the modified plugin is attached. In OctoPrint, go to Plugin Manager > Add Plugins > Upload from File and upload that. It works!

Hope this helps someone.

[ArcWelderPlugin-1.1.0rc4_FIX.zip](https://github.com/user-attachments/files/23403401/ArcWelderPlugin-1.1.0rc4_FIX.zip)

**Comment by CristianFiles** [comment]
Since the fix in the previous answer didn't work for me I decided to make it work **specifically** for Octo4a.

I basically removed any reference to distutils (since it is completely removed in Python 3.12) and any reference to C compilers like Cygwin or other stuff that doesn't exist for Octo4a.
I also added a dependency to the requirement.txt file which is an equivalent to the LooseVersion package which didn't work for some reason.
I could've done it way cleaner but if you just need to make it work it will be fine.

If I had to make it run on other platforms I would take the previous answer's fix and comment/uncomment dependencies to the C compilers in setup.py based on what you're working with since that is the source of errors.

[ArcWelderPlugin-1.1.0rc4_Octo4a-FIX.zip](https://github.com/user-attachments/files/26290106/ArcWelderPlugin-1.1.0rc4_Octo4a-FIX.zip)
