### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by drdpj** [FormerLurker/ArcWelderPlugin#254]
Hello, 
Installing from marketplace on the latest version of octoprint on an orange pi zero H2... It installs but then completely barfs when trying to activate:

```
2023-02-12 10:40:22,693 - octoprint.plugin.core - ERROR - Error loading plugin arc_welder
Traceback (most recent call last):
  File "/home/daniel/venv/lib/python3.9/site-packages/octoprint/plugin/core.py", line 1274, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/daniel/venv/lib/python3.9/site-packages/octoprint/plugin/core.py", line 52, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/daniel/venv/lib/python3.9/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
  File "/home/daniel/venv/lib/python3.9/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/daniel/venv/lib/python3.9/site-packages/octoprint_arc_welder/__init__.py", line 35, in <module>
    from six import string_types
ImportError: cannot import name 'string_types' from 'six' (/home/daniel/venv/lib/python3.9/site-packages/six.py)
```
I have removed and reinstalled six several times but it's not playing ball... Any ideas?

**Comment by drdpj** [comment]
And for some reason after several more reboots it's suddenly started working. I have no idea 🙄 As you were!
