### ISSUE TITLE
"Unknown error while checking for update, please check the logs" when using software update screen of octopi

### ISSUE THREAD

**Issue by Dweinbach** [FormerLurker/ArcWelderPlugin#265]
I just got this while checking for software updates in octopi:
![image](https://github.com/FormerLurker/ArcWelderPlugin/assets/29680000/7781f4d7-67b0-43de-a849-d08e18cd19f8)

and here is the corresponding log entry:
```
2024-04-29 21:34:28,634 - octoprint.plugins.softwareupdate - ERROR - Could not check arc_welder for updates
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 1851, in _get_current_version
    information, is_current = version_checker.get_latest(
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 274, in get_latest
    raise ConfigurationInvalid(
octoprint.plugins.softwareupdate.exceptions.ConfigurationInvalid: Update configuration for arc_welder of type github_release needs all of user, repo and current set and not None
```
ArcWelder itself seems to be running/working.

**Comment by Dweinbach** [comment]
duplicate of issue #235
