### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by eefweenink** [FormerLurker/ArcWelderPlugin#267]
Since last update of octoprint (I think, but not sure), I get this error on every print I upload. 
Arc_welder runs fine, untill finished and throws an error. 
In log file I find this: 

2024-05-03 05:58:27,320 - arc_welder.preprocessor - ERROR - An unhandled exception occurred while preprocessing the gcode file.
Traceback (most recent call last):
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint_arc_welder/preprocessor.py", line 105, in run
    self._process(path, processor_args, additional_metadata, is_manual_request)
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint_arc_welder/preprocessor.py", line 166, in _process
    self._success_callback(encoded_results, path, processor_args, additional_metadata, is_manual_request)
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint_arc_welder/__init__.py", line 678, in preprocessing_success
    new_path, new_name, metadata = self.save_preprocessed_file(
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint_arc_welder/__init__.py", line 472, in save_preprocessed_file
    self._file_manager.add_file(
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint_PrintTimeGenius/__init__.py", line 579, in new_add_file
    return self._file_manager.original_add_file(destination, path, file_object, links, allow_overwrite, printer_profile, None, display)
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint/filemanager/__init__.py", line 728, in add_file
    path_in_storage = self._storage(location).add_file(
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint/filemanager/storage.py", line 963, in add_file
    file_object.save(file_path)
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint/filemanager/util.py", line 102, in save
    shutil.copyfileobj(source, dest)
  File "/usr/lib/python3.9/shutil.py", line 205, in copyfileobj
    buf = fsrc_read(length)
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint/filemanager/util.py", line 211, in read
    line = self.input_stream.readline()
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint/filemanager/util.py", line 230, in readinto
    read = self.read(n)
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint/filemanager/util.py", line 211, in read
    line = self.input_stream.readline()
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint/filemanager/util.py", line 230, in readinto
    read = self.read(n)
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint/filemanager/util.py", line 214, in read
    processed_line = self.process_line(line)
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint_SlicerEstimator/metadata.py", line 32, in process_line
    return_line = self._metadata_obj.process_line(return_line)
  File "/home/eef/oprint/lib/python3.9/site-packages/octoprint_SlicerEstimator/metadata.py", line 109, in process_line
    decoded_line = line.decode()
AttributeError: 'NoneType' object has no attribute 'decode'

Is this an ArcWelder error? Should I change the settings in PrusaSlicer or Octoprint? 
Or is this a Slicer_Estimator problem?

**Comment by Thynix** [comment]
The traceback suggests SlicerEstimator - does it still happen if you uninstall SlicerEstimator?
