### ISSUE TITLE
Octoprint Software Update Error

### ISSUE THREAD

**Issue by AndrewLuebke** [FormerLurker/ArcWelderPlugin#89]
In Octoprint 1.5.1 (and 1.5.0) on Raspberry Pi I get the following error:

![2020-12-06 10_09_17-OctoPi - 1  OctoPrint  — Mozilla Firefox](https://user-images.githubusercontent.com/45699172/101288393-2daa4180-37ab-11eb-855f-78e606e4edfe.png)

in the log I see:

2020-12-06 10:05:17,762 - octoprint.plugins.softwareupdate - ERROR - Could not check arc_welder for updates
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 1496, in _get_current_version
    target, check, online=online, credentials=credentials
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 305, in get_latest
    target
octoprint.plugins.softwareupdate.exceptions.ConfigurationInvalid: Update configuration for arc_welder of type github_release needs all of user, repo and current set and not None

I've tried reinstalling Arc Welder with the same result.  This is sort of a cosmetic problem for me since the plugin still works fine and I could reinstall by hand if I want to update but it would be nice to have Octoprint tell me when a new version is available.

**Comment by FormerLurker** [comment]
This is fixed in the latesy devel branch, which I am still working on.  It is pretty close to a devel/rc.  I will post a link here so you can test the update fix.  Thanks for your report!

**Comment by AndrewLuebke** [comment]
Thanks, I just saw the other issue report in closed.  I'll try it when you have a link for me.

**Comment by holocronology** [comment]
Still doing this in the 1.5.2 hotfix update.

**Comment by St-Aris** [comment]
This appears on Octoprint 1.8.0 (possibly earlier versions too - only noticed it when I upgraded)

![image](https://user-images.githubusercontent.com/16673089/168825626-1b3bf49b-b8dc-433e-b5c9-d2b38e786e8b.png)

**Comment by FormerLurker** [comment]
Sigh...  I was finally packaging up this version for a deploy, but this is a showstopper.  Will get on it.  Thanks for the report since this is probably the most difficult thing to test for.

**Comment by St-Aris** [comment]
No worries - let me know if you want any info to help you get to the bottom of it.
